# =============================================================================
# MASTER RUNNER: Biodiversity and Energy System Planning QLD 2025
# =============================================================================
# Author: Andrew Rogers
# LLMs used: Claude AI and Gemini
# Date: Jan 2026; Updated: Mar 2026
# =============================================================================
# Purpose: Executes the full analysis pipeline in two independent steps.
#
#   Step 1 — Main manuscript figures and tables:
#     Figure 1a — Biodiversity prioritisation map (ArcGIS Pro — path printed to console)
#     Figure 1b-e — VRE siting maps (domestic_export_map_iterations.R)
#     Table 1   — All-MNES scenario coverage (Mean_spp_scenario_coverage.R)
#     Table 1   — CE/EN mean coverage (data table path printed to console)
#     Figure 2  — NPV bar chart (NPV_bar_plot.R)
#     Figure 3  — New TX build length (tx_length_figure.R)
#     Figure 4  — Cost increase line plot (percent cost increase_line plot.R)
#
#   Step 2 — Supplementary material figures:
#     Supp. Fig 1D — Zonation performance curves (Zonation curves.R)
#     Supp. Fig 2  — Zero-coverage species map (zero_coverage_species.R)
#     Supp. Fig 6  — Exclusion area barplot (exclusion_overlap_barplot.R)
#
#   NOTE: Figure 3 inputs are pre-computed by tx_run_all.R (transmission pipeline).
#   Set run_step1 / run_step2 to TRUE/FALSE to run steps independently.
# =============================================================================

# 1. INITIAL SETUP
if (!require(pacman)) install.packages("pacman")
pacman::p_load(here, magick)

# --- USER CONTROL: Set which steps to run ---
run_step1 <- TRUE   # Paper figures
run_step2 <- TRUE   # Land-use maps and barplots

cat("\n Starting Full Analysis Pipeline...\n")
start_time <- Sys.time()

# =============================================================================
# 2. DEFINE PIPELINE STEPS
# =============================================================================

# Step 1: main manuscript figures/tables
pipeline_step1 <- list(
  "Figure 1b-e (VRE maps)"  = here("Energy system and transmission mapping_code", "domestic_export_map_iterations.R"),
  "Table 1 (all MNES)"      = here("species_code", "Mean_spp_scenario_coverage.R"),
  "Figure 2 (NPV)"          = here("Figure_code", "NPV_bar_plot.R"),
  "Figure 3 (TX length)"    = here("Figure_code", "tx_length_figure.R"),
  "Figure 4 (costs)"        = here("Figure_code", "percent cost increase_line plot.R")
)

# Step 2: supplementary figures
pipeline_step2 <- list(
  "Supp. Fig 1D (Zonation curves)"    = here("Figure_code", "Zonation curves.R"),
  "Supp. Fig 2 (zero-coverage spp.)"  = here("species_code", "zero_coverage_species.R"),
  "Supp. Fig 6 (exclusion barplot)"   = here("Figure_code", "exclusion_overlap_barplot.R")
)

# =============================================================================
# 3. EXECUTION ENGINE
# =============================================================================

run_pipeline <- function(pipeline, step_label) {
  log <- data.frame(
    Step   = names(pipeline),
    Status = "Pending",
    Time   = NA_character_,
    stringsAsFactors = FALSE
  )
  for (i in seq_along(pipeline)) {
    step_name <- names(pipeline)[i]
    step_path <- pipeline[[i]]
    cat(sprintf("\n--- %s: %s ---\n", step_label, step_name))
    if (file.exists(step_path)) {
      tryCatch({
        source(step_path)
        log$Status[i] <- "Success \u2705"
      }, error = function(e) {
        log$Status[i] <<- paste("Failed \u274c:", e$message)
      })
    } else {
      log$Status[i] <- "File Not Found \u274c"
    }
    log$Time[i] <- format(Sys.time(), "%H:%M:%S")
  }
  log
}

all_logs <- list()

if (run_step1) {
  cat("\n", strrep("=", 50), "\n")
  cat("STEP 1: Main Manuscript Figures & Tables\n")
  cat(strrep("=", 50), "\n")

  # Figure 1a — styled in ArcGIS Pro from Zonation rankmap.tif; no R script
  source(here::here("_paths.R"))
local_override <- here::here("_paths_local.R")
if (file.exists(local_override)) {
  source(local_override)
  cat(">>> Using local path overrides from _paths_local.R\n")
}
  cat("\n--- Step 1: Figure 1a (Biodiversity prioritisation map) ---\n")
  cat("  NOTE: Figure 1a was produced in ArcGIS Pro using the Zonation rankmap.\n")
  cat("  Source raster: ", paths$rankmap, "\n")
  cat("  Figure 1b-e will be generated by the next pipeline step.\n")
  cat("  Status: Skipped (ArcGIS Pro output) \u2139\ufe0f\n")

  cat("\n--- Step 1: Table 1 (CE/EN mean coverage) ---\n")
  cat("  NOTE: CE/EN mean coverage results are pre-computed.\n")
  cat("  Data table: ", here("results", "tables", "CE_EN_mean_coverage_results.csv"), "\n")
  cat("  To regenerate, run: Figure_code/Critically_endangered_mean_coverage_and_line_plot.R\n")
  cat("  Status: Skipped (pre-computed) \u2139\ufe0f\n")

  all_logs[["Step 1: Main Manuscript Figures & Tables"]] <- run_pipeline(pipeline_step1, "Step 1")
}

if (run_step2) {
  cat("\n", strrep("=", 50), "\n")
  cat("STEP 2: Supplementary Material Figures\n")
  cat(strrep("=", 50), "\n")
  all_logs[["Step 2: Supplementary Figures"]] <- run_pipeline(pipeline_step2, "Step 2")
}

# =============================================================================
# 4. FINAL STATUS REPORT
# =============================================================================

cat("\n", strrep("=", 50), "\n")
cat("FINAL PIPELINE REPORT\n")
cat(strrep("=", 50), "\n")

for (label in names(all_logs)) {
  cat(sprintf("\n%s\n", label))
  print(all_logs[[label]], row.names = FALSE)
}

end_time <- Sys.time()
cat(sprintf("\nTotal Runtime: %0.2f minutes\n",
            as.numeric(difftime(end_time, start_time, units = "mins"))))
cat("All outputs are available in the /results folder.\n")
cat(strrep("=", 50), "\n")

# =============================================================================
# 5. SESSION INFO (for reproducibility)
# =============================================================================

cat("\nSESSION INFO\n")
cat(strrep("=", 50), "\n")
print(sessionInfo())
