# =============================================================================
# TRANSMISSION PIPELINE MASTER RUNNER
# =============================================================================
# Author: Andrew Rogers
# LLMs used: Claude AI
# Date: Mar 2026
# =============================================================================
# Purpose: Executes the full transmission analysis pipeline in order, skipping
#          steps whose outputs already exist (controlled by overwrite_mode).
#
# PRIMARY GOAL — produces Figure 3 inputs:
#   results/transmission_processing/tx1|tx2/
#     QLD_threshold_tx_new_summaries/QLD_threshold_tx_new_summary.csv
#   then copies to:
#   BESP_data_qld_2025/Electricity_Transmission_Lines/Tx_outputs/
#     tx1_domestic_transmission/QLD_threshold_tx_new/QLD_threshold_tx1_new_summary.csv
#     tx2_domestic_transmission/QLD_threshold_tx_new/QLD_threshold_tx2_new_summary.csv
#
#   Figure 3 is generated by Figure_code/tx_length_figure.R via _RUN_ALL.R.
#
# PIPELINE OVERVIEW
# ─────────────────────────────────────────────────────────────────────────────
#  PREREQ  QLD_reproject_tx_lines.R        Reproject existing TX (one-off)
#
#  For each scenario in `scenarios` (tx1, tx2):
#  Step 1   Transmission_processing.R       GDB → GPKG + TX_domestic_layers/
#  Step 2   Transmission_save_layers_as_shapefiles.R  GPKG → shapefiles
#              (optional: Step 1 already saves shapefiles; Step 2 is a
#               fallback if you want to re-extract without re-running Step 1)
#  Step 3   QLD_new_tx_processing_summary.R New TX lengths → summary CSV
#  Step 3b  [auto] Copy summary CSV → Tx_outputs/ for use by tx_length_figure.R
#
# SUPPORTING ANALYSES (run_supporting = TRUE):
#  For each scenario:
#  Supp 1   Transmission_clip_join_w_existing.R   Overlap tables
#  Supp 2   QLD_exisitng_model_tx_max_join.R      Max kV join
#  Supp 3   QLD_modelled_tx_easement_area.R        Easement area calc
#  Supp 4   QLD_tranmission_summaries_modelled_existing.R  Alt summary
#  Supp 5   Transmission_upgrade_calculation.R    Upgrade area (both scenarios)
#
# NOTE: QLD_summarize_exisiting_in_simiplified_tx.R is a utility fragment
#       that requires `simplified_tx` to be loaded manually — excluded here.
# =============================================================================

if (!require(pacman)) install.packages("pacman")
pacman::p_load(here, readr)
source(here::here("_paths.R"))
local_override <- here::here("_paths_local.R")
if (file.exists(local_override)) {
  source(local_override)
  cat(">>> Using local path overrides from _paths_local.R\n")
}

# =============================================================================
# USER CONTROL
# =============================================================================

scenarios      <- c("tx1", "tx2")  # scenarios to process
overwrite_mode <- FALSE            # TRUE = rerun even if outputs exist

run_prereq     <- TRUE   # Reproject existing TX lines (safe to leave TRUE;
                         # skips automatically if output already exists)
run_primary    <- TRUE   # Figure 3 inputs (Steps 1-3; figure generated by _RUN_ALL.R)
run_supporting <- FALSE  # Supporting analyses (Supp 1-5, not needed for Fig 3)

# =============================================================================
# HELPERS
# =============================================================================

script_dir <- here("Energy system and transmission mapping_code",
                   "transmission_mapping")

run_step <- function(label, script_name, log) {
  path <- file.path(script_dir, script_name)
  cat(sprintf("\n--- %s ---\n", label))
  if (!file.exists(path)) {
    log[[label]] <- "File Not Found \u274c"
    return(log)
  }
  tryCatch({
    source(path)
    log[[label]] <- "Success \u2705"
  }, error = function(e) {
    log[[label]] <<- paste("Failed \u274c:", e$message)
  })
  log
}

log <- list()
start_time <- Sys.time()
cat("\n=== TRANSMISSION PIPELINE STARTING ===\n")
cat(sprintf("Scenarios : %s\n", paste(scenarios, collapse = ", ")))
cat(sprintf("Overwrite : %s\n", overwrite_mode))

# =============================================================================
# PREREQUISITE: Reproject existing TX lines (one-off, skip if output exists)
# =============================================================================

if (run_prereq) {
  proj_shp <- file.path(dirname(paths$existing_tx), "QLD_existing_tx_projected.shp")
  if (!file.exists(proj_shp) || overwrite_mode) {
    log <- run_step("PREREQ: Reproject existing TX lines",
                    "QLD_reproject_tx_lines.R", log)
  } else {
    cat("\n--- PREREQ: Reproject existing TX lines --- Exists (skip)\n")
    log[["PREREQ: Reproject existing TX lines"]] <- "Skipped (exists) \u2139\ufe0f"
  }
}

# =============================================================================
# PRIMARY PIPELINE — run for each scenario
# =============================================================================

if (run_primary) {

  for (sc in scenarios) {
    tx_scenario <- sc   # set for child scripts (if (!exists) guard)
    tx_proc     <- if (sc == "tx1") tx1_processing else tx2_processing

    cat(sprintf("\n%s\n", strrep("=", 60)))
    cat(sprintf("SCENARIO: %s\n", toupper(sc)))
    cat(strrep("=", 60), "\n")

    # ------------------------------------------------------------------
    # Step 1: Extract from GDB → GeoPackage + per-threshold shapefiles
    # ------------------------------------------------------------------
    gpkg_out <- file.path(tx_proc, "split_tx.gpkg")
    shp_out  <- file.path(tx_proc, "TX_domestic_layers")

    if (!file.exists(gpkg_out) || !dir.exists(shp_out) || overwrite_mode) {
      log <- run_step(
        sprintf("[%s] Step 1: GDB → shapefiles (Transmission_processing)", sc),
        "Transmission_processing.R", log)
    } else {
      cat(sprintf("\n--- [%s] Step 1: GDB → shapefiles --- Exists (skip)\n", sc))
      log[[sprintf("[%s] Step 1: GDB → shapefiles", sc)]] <- "Skipped (exists) \u2139\ufe0f"
    }

    # ------------------------------------------------------------------
    # Step 2: GPKG → individual shapefiles (optional fallback)
    #         Skip if TX_domestic_layers/ already populated by Step 1
    # ------------------------------------------------------------------
    n_shp <- length(list.files(shp_out, pattern = "\\.shp$"))
    if (n_shp == 0 || overwrite_mode) {
      log <- run_step(
        sprintf("[%s] Step 2: GPKG → shapefiles (save_layers)", sc),
        "Transmission_save_layers_as_shapefiles.R", log)
    } else {
      cat(sprintf("\n--- [%s] Step 2: GPKG → shapefiles --- %d shapefiles exist (skip)\n",
                  sc, n_shp))
      log[[sprintf("[%s] Step 2: GPKG → shapefiles", sc)]] <- "Skipped (exists) \u2139\ufe0f"
    }

    # ------------------------------------------------------------------
    # Step 3: New TX length summary (st_difference vs existing network)
    # TARGET: QLD_threshold_tx_new_summaries/QLD_threshold_tx_new_summary.csv
    # ------------------------------------------------------------------
    summary_csv <- file.path(tx_proc, "QLD_threshold_tx_new_summaries",
                             "QLD_threshold_tx_new_summary.csv")

    if (!file.exists(summary_csv) || overwrite_mode) {
      log <- run_step(
        sprintf("[%s] Step 3: New TX length summary", sc),
        "QLD_new_tx_processing_summary.R", log)
    } else {
      cat(sprintf("\n--- [%s] Step 3: New TX length summary --- Exists (skip)\n", sc))
      log[[sprintf("[%s] Step 3: New TX length summary", sc)]] <- "Skipped (exists) \u2139\ufe0f"
    }

    # ------------------------------------------------------------------
    # Step 3b: Copy summary CSV to Tx_outputs/ for use by tx_length_figure.R
    # ------------------------------------------------------------------
    dest_csv <- file.path(paths$energy_outputs,
                          paste0(sc, "_new_transmission_summary.csv"))

    if (file.exists(summary_csv) && (!file.exists(dest_csv) || overwrite_mode)) {
      if (!dir.exists(paths$energy_outputs)) {
        dir.create(paths$energy_outputs, recursive = TRUE)
      }
      file.copy(summary_csv, dest_csv, overwrite = TRUE)
      cat(sprintf("\n✓ [%s] Copied summary CSV to Energy_system_model_outputs/\n", sc))
      log[[sprintf("[%s] Step 3b: Copy CSV to energy_outputs", sc)]] <- "Success \u2705"
    } else if (file.exists(dest_csv)) {
      cat(sprintf("\n--- [%s] Step 3b: Copy CSV --- Destination exists (skip)\n", sc))
      log[[sprintf("[%s] Step 3b: Copy CSV to energy_outputs", sc)]] <- "Skipped (exists) \u2139\ufe0f"
    } else {
      cat(sprintf("\n--- [%s] Step 3b: Copy CSV --- Source not found, skipping\n", sc))
      log[[sprintf("[%s] Step 3b: Copy CSV to energy_outputs", sc)]] <- "Skipped (source missing) \u26a0\ufe0f"
    }
  }

}

# =============================================================================
# SUPPORTING ANALYSES
# =============================================================================

if (run_supporting) {
  cat(sprintf("\n%s\n", strrep("=", 60)))
  cat("SUPPORTING ANALYSES\n")
  cat(strrep("=", 60), "\n")

  for (sc in scenarios) {
    tx_scenario <- sc
    cat(sprintf("\n  --- Supporting: %s ---\n", toupper(sc)))

    log <- run_step(sprintf("[%s] Supp 1: Clip/join w existing", sc),
                    "Transmission_clip_join_w_existing.R", log)

    log <- run_step(sprintf("[%s] Supp 2: Max kV join", sc),
                    "QLD_exisitng_model_tx_max_join.R", log)

    log <- run_step(sprintf("[%s] Supp 3: Easement area", sc),
                    "QLD_modelled_tx_easement_area.R", log)

    log <- run_step(sprintf("[%s] Supp 4: Model/existing summary", sc),
                    "QLD_tranmission_summaries_modelled_existing.R", log)
  }

  # Upgrade calculation handles both scenarios internally
  log <- run_step("Supp 5: Upgrade area calculation (both scenarios)",
                  "Transmission_upgrade_calculation.R", log)
}

# =============================================================================
# FINAL STATUS REPORT
# =============================================================================

cat(sprintf("\n%s\n", strrep("=", 60)))
cat("TRANSMISSION PIPELINE REPORT\n")
cat(strrep("=", 60), "\n")

for (nm in names(log)) {
  cat(sprintf("  %-65s %s\n", nm, log[[nm]]))
}

elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "mins"))
cat(sprintf("\nTotal runtime: %.1f minutes\n", elapsed))

# Final output check
cat("\nKey output files:\n")
for (sc in scenarios) {
  tx_proc  <- if (sc == "tx1") tx1_processing else tx2_processing
  csv_proc <- file.path(tx_proc, "QLD_threshold_tx_new_summaries",
                        "QLD_threshold_tx_new_summary.csv")
  csv_dest <- file.path(paths$energy_outputs,
                        paste0(sc, "_new_transmission_summary.csv"))
  cat(sprintf("  [%s] Processing summary: %s  %s\n",
              sc, csv_proc, if (file.exists(csv_proc)) "\u2705" else "\u274c"))
  cat(sprintf("  [%s] Energy outputs CSV: %s  %s\n",
              sc, csv_dest, if (file.exists(csv_dest)) "\u2705" else "\u274c"))
}
cat("  Figure 3: generated by Figure_code/tx_length_figure.R via _RUN_ALL.R\n")
cat("\n=== TRANSMISSION PIPELINE COMPLETE ===\n")
